image: buildpack-deps:curl

definitions:
  caches:
    sonar: ~/.sonar
  services:
    docker:
      memory: 4096 
clone:
  depth: 50


pipelines:
  branches:

  "main":
      - step:
          name: Check
          script:
            - bash ./call_remote_hook.sh --url "$HOOK_DEPLOY_CECO13_URL" --secret "$HOOK_DEPLOY_CECO13_SECRET" --hook "$HOOK_CHECK_NAME" 

      - step:
          name: SonarQube analysis
          size: 2x 
          services:
            - docker 
          caches:
            - sonar
          script:
            - pipe: sonarsource/sonarqube-scan:3.0.2
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL}
                SONAR_TOKEN: ${SONAR_TOKEN}
                SONAR_SCANNER_OPTS: "-Xmx3072m" 

    "release/production":
      - step:
          name: Call remote hook (Deploy to CECO13)
          deployment: Production
          script:
            - chmod +x ./call_remote_hook_deploy.sh
            - ./call_remote_hook_deploy.sh --url "$HOOK_DEPLOY_CECO13_URL" --hook "$HOOK_DEPLOY_NAME" --secret "$HOOK_DEPLOY_CECO13_SECRET"

