services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf"
      ZOOKEEPER_ALLOW_SASL_ANONYMOUS: "false"
    volumes:
      - ./secrets/kafka:/etc/kafka
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - confluent

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: key_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required        # set 'required' if you want mTLS
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: "1"   # single-broker cluster
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "true"  # auto-create _confluent-metrics
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,EXTERNAL://kafka.ecoceutics.com:9092
      # tell the JVM where JAAS is:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf -Dzookeeper.sasl.client=true -Dzookeeper.sasl.client.username=kafka"
    volumes:
      - ./secrets/kafka:/etc/kafka/secrets
    healthcheck:
      # Succeeds when broker answers the metadata call
      test: ["CMD", "bash", "-lc", "kafka-broker-api-versions --bootstrap-server localhost:29092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks: 
      - confluent

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -f http://localhost:8081/subjects || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - confluent

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    hostname: control-center
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_CONNECT_CONNECT_CLUSTER: "http://connect:8083"
    networks:
      - confluent
  connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    hostname: connect
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      CONNECT_LISTENERS: "http://localhost:8083"       
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"  
      CONNECT_REST_ADVERTISED_PORT: "8083"             
    volumes:
      - ./kafka-connect:/etc/kafka-connect/jars
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -sf http://localhost:8083/connectors || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: 
      - confluent

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - confluent

  apiserver:
    image: apache/airflow:3.1.3
    # apiserver
    command: >
      bash -lc "exec airflow api-server"
    depends_on:
      - postgres
      - scheduler
      - dag-processor
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
      # AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      # AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: this_is_a_very_secured_key
      # AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_API_JWT_SECRET}
      # AIRFLOW__API_AUTH__JWT_ALGORITHM: HS256
      # AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      FORWARDED_ALLOW_IPS: "*"
      # AIRFLOW__API__BASE_URL: ${AIRFLOW_API_BASE_URL}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./httpd/airflow.cfg:/airflow.cfg
    ports:
      - "8080:8080"
    networks:
      - confluent
  reverse-proxy:
      image: httpd:2.4
      ports:
        - "8088:80"
        - "443:443"
      volumes:
        - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      depends_on:
        - apiserver
      networks:
        - confluent

  scheduler:
    image: apache/airflow:3.1.3
    command: bash -lc "pip install --no-cache-dir -r /opt/airflow/requirements.txt  && exec airflow scheduler"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
      AIRFLOW__API__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://127.0.0.1:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_API_JWT_SECRET}
      AIRFLOW__API_AUTH__JWT_ALGORITHM: HS256
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      FORWARDED_ALLOW_IPS: "*"
      # AIRFLOW__API__BASE_URL: ${AIRFLOW_API_BASE_URL}
    networks:
      - confluent

  dag-processor:
    image: apache/airflow:3.1.3
    command: bash -lc "pip install --no-cache-dir -r /opt/airflow/requirements.txt && exec airflow dag-processor"
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://127.0.0.1:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_API_JWT_SECRET}
      AIRFLOW__API_AUTH__JWT_ALGORITHM: HS256 
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET}
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      FORWARDED_ALLOW_IPS: "*"
      # AIRFLOW__API__BASE_URL: ${AIRFLOW_API_BASE_URL}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      # - ./logs:/opt/airflow/logs
    networks:
      - confluent

  spark-master:
      image: apache/spark:4.0.1-scala2.13-java21-python3-r-ubuntu
      command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      ports:
        - "9090:8080"
        - "7077:7077"
      networks:
        - confluent
  spark-worker:
    image: apache/spark:4.0.1-scala2.13-java21-python3-r-ubuntu
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - confluent
  
  python-master:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: python-master
    working_dir: /work
    tty: true
    stdin_open: true
    volumes:
      - ./apps:/work/apps        
      - ./data:/work/data        
      - ~/.ssh:/home/app/.ssh:ro 
    networks:
      - confluent  

networks:
  confluent:
    driver: bridge

