#Dominio proncipal del Hub
Define DATAHUB_MAIN_DOMAIN datahub.ecoceutics.com

#Subdominios para cada elemento del Hub
Define DATAHUB_AIRFLOW_DOMAIN datahub-airflow.ecoceutics.com
Define DATAHUB_SPARK_DOMAIN datahub-spark.ecoceutics.com
Define DATAHUB_KAFKA_DOMAIN datahub-kafka.ecoceutics.com

#Archivo de autenticación para elementos de Hub sensibles
Define DATAHUB_AUTH_USER_FILE /etc/apache2/.htpasswd-datahub

#Document root del Hub Principal
Define DATAHUB_DOCUMENT_ROOT /var/www/xxxxxxx
