Define DATAHUB_MAIN_DOMAIN datahub.ecoceutics.com
Define DATAHUB_AIRFLOW_DOMAIN datahub-airflow.ecoceutics.com
Define DATAHUB_SPARK_DOMAIN datahub-spark.ecoceutics.com
Define DATAHUB_KAFKA_DOMAIN datahub-kafka.ecoceutics.com
